### PR TITLE
code complete and passed initial testing

### PR DESCRIPTION
**Pull request by divfor**
Summary
------------
This enhancement is to simplify locator usage. Generally it is difficult for junior engineers and customer to understand the locators written in user keywords or test steps. It would be better if they can use Web UI texts/words prompting for target element instead of locators.  The real locators  could be mapped by prompting UI text in variable files created and maintained by senior engineers. If so, the test cases will be more easier to read.

The basic thought is to build page dictionary per URL, and let element find function to parse mapped locator again if first locator parsing returns 'None' prefix. 

Usage:
---------
Setup a dictionary named PAGE_DICT_NAMES, and add key-value to it.
key: the short part of page's URL stripping host name/port and trailing chars starting from first '?'    value: the name of page dictionary
```robotframework
    #method 1: user keyword to create
    ${name_dicts}    Create Dictionary    configure/general_cfg_user.ink    page_configure_user
    Set Global Variable    ${PAGE_DICT_NAMES}    ${name_dicts}
    #method 2: import variables in scope setup or on demand
    Import Variables    path/to/page_dict_names.py
```

Create dictionary for each page (URL)
```robotframework
    #method 1: user keyword to create
    ${page_configure_user}    Create Dictionary    Input user name    id\=username    Input password    id\=password
    #method 2: import variables on demand    ${page}
    Import Variables    path/to/page_dicts.py
```

How to get short name of URL?
-------------------------------------------
keyword 'Get Location Short Name'

### CODE REVIEW

**Comment by zephraph** [comment]
I've looked over this, but it seems to me like it makes the process more complicated. 

Could you give me example of how this would be more beneficial over the current method?

**Comment by divfor** [comment]
example usage:
1. create a py file for dicts to store dictionary names and their content - mappings of 'element_description_text':'locator'
```python
PAGE_DICT_NAMES = {
    'DEFAULT_PAGE': 'page_dict_main',
    'compare/browser/mybrowser.html': 'page_dict_compareto'
}

page_dict_main = {
    'Compare to...': 'css=#score > div.wrapper > div > a.button.compare'
}

page_dict_compareto = {
    'browsers': 'css=body > div:nth-child(3) > div > div.paper.hasNavigation > ul > li.selected > a',
    'features': 'css=body > div:nth-child(3) > div > div.paper.hasNavigation > ul > li:nth-child(2) > a'
}
```

2. import it in proper scope level and use element_description_text as locator for keywords:
```robotframework
*** Settings ***
Library           Selenium2Library
Variables         keywords/page_dicts.py

*** Test Cases ***
Open Github
    Open Browser    http://html5test.com/    gc
    Comment    Sleep    3
    Click Element    Compare to...
    Click Element    features
    Sleep    2
    [Teardown]    Close All Browsers
```

**Comment by zephraph** [comment]
I think you're adding an unnecessary layer of complexity here. If you want your tests to be more legible to customers then you can create a resource file with user keywords that simplify each of your test steps. Adding this dictionary doesn't make it any easier to maintain tests, and I'd argue that this approach actually makes it harder for test engineers to see what's going on. 

With that being said, there's no reason you can't do something similar to what you're wanting to do utilizing how everything works right now. 

```python
# locators.py
compare_button = 'css=#score > div.wrapper > div > a.button.compare'
features_link = 'css=body > div:nth-child(3) > div > div.paper.hasNavigation > ul > li:nth-child(2) > a'
```

```robotframework
*** Settings ***
Library        Selenium2Library
Variables    locators.py

*** Test Cases ***
Open Html5Test
  [Setup]  Open Browser  http://html5test.com/  firefox
  Sleep  3
  Click Element    ${Compare Button}
  Click Element    ${Features Link}
  Sleep  3
  [Teardown]  Close All Browsers
```

If even that is too verbose then add a resource file to go along with every test

```robotframwork
*** Settings ***
Library        Selenium2Library

*** Keywords ***
Click the compare button
   Click Element  ${Compare Button}

Click the feature link
   Click Element  ${Feature Link}
```

Ultimately though, I'm afraid you'll find that by adding all these layers of abstraction you're going to greatly increase the level of effort required to maintain your tests.

**Comment by divfor** [comment]
Thank you Zephraph for clarification. Your review is helpful to me.
The initial requirement for this is that we want to convert manual testers to automation QA Engineers. And then I found that the more important thing is to extend automation from regression testing to product feature development that QA should be able to write tests/keywords even if web pages are not finalized yet. It depends on defining page element objects as DEV-QA interface which should be completed by feature design stage. Element element object can be stored in ether database or python variable file, and indexed by a fixed master key which is stable for QA after design stage. The value parts of element object, like UI description, element locator,  parent or childs, may be changed in the whole development period. It is DEV to create/update the data of element objects in product code line other than automation code line, so there will be less maintenance work for QA.
As I know, the QA automation teams for www.taobao.com (Alibaba) had to design their own automation framework named Automan due to lack of the split between DEV and QA after investigating  many automation frameworks.

**Comment by zephraph** [comment]
What you're describing is probably going to be hard to enforce unless you have high procedure adherence from both your QA and DEV teams. In a general sense the tests can be written out using broad keywords that can be refined later to achieve a successful test. That's probably not the best approach though. 

What I would do if I were in your shoes is push strongly for ids on all elements that need to be tested. Make it a policy not to change an id unless there's a strong reason to do so and ensure QA gets notified of the change. I think that would be much easier to enforce than requiring your developers to manage some database/list of testable components.

**Comment by emanlove** [comment]
I've not dived deeply into your code but what you are describing here sounds like the page object model which the [NCBI team has implemented](https://github.com/ncbi/robotframework-pageobjects). You might look at their work but I agree with @zephraph as what you are describing seems more work than not.

You could also teach your QA team how to find elements using tools like Firebug and Firepath. I've done this at our organization with QA whom some have programming backgrounds and so do not. I find their skill as critical thinkers is just as important as programming skills. There is a balance between these skills and I see with our team that there is an opportunity to share strengths and work as a team. One strong advantage/skill that our QA team, which historically has been almost exclusively manual with some members with a little previous automation experience, has is that our applications have long been web-based. So the browser is a natural environment to work within.  I could see manual QA teams whose products have just recently become web-based  and don't have a history of testing web-based applications at a disadvantage.

**Pull request merged**
